{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
{{- end }}